// OpenCode Plugin 安装器 — 生成项目级 JS plugin 和当前终端 launcher
package io.github.q110.aiterminaltools.monitor

import com.intellij.openapi.diagnostic.Logger
import com.intellij.openapi.project.Project
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.attribute.PosixFilePermission

/**
 * `.opencode/plugins` 是项目级目录，不能写入 tab 专属的 token/port。
 * 生成的 JS plugin 会在运行时从当前 OpenCode 进程环境读取 AITT_*。
 */
class AiTurnOpenCodeInstaller(
    private val project: Project
) {
    private val log = Logger.getInstance(AiTurnOpenCodeInstaller::class.java)

    /** 安装 OpenCode project plugin，并返回当前 tab 专用 launcher 脚本路径 */
    fun installOpenCodePlugin(tabId: String, token: String, port: Int): AiTurnHookInstaller.LauncherPaths {
        val projectBasePath = project.basePath
            ?: throw IllegalStateException("Project base path is null")
        val basePath = Path.of(projectBasePath)
        val toolsDir = basePath.resolve(".idea").resolve("ai-terminal-tools")
        Files.createDirectories(toolsDir)

        writeJsPlugin(basePath)

        return writeLauncherScripts(toolsDir, tabId, token, port)
    }

    private fun writeJsPlugin(basePath: Path) {
        val pluginsDir = basePath.resolve(".opencode").resolve("plugins")
        Files.createDirectories(pluginsDir)
        val pluginFile = pluginsDir.resolve("ai-terminal-tools.js")

        // JS 内容保持无 tab 状态，避免多个 OpenCode tab 重写同一个 plugin 后串台。
        val js = buildString {
            appendLine("// Auto-generated by AI Terminal Tools")
            appendLine("// Sends OpenCode turn/file events to the IDEA plugin.")
            appendLine("// Runtime config is read from the current OpenCode process environment.")
            appendLine()
            appendLine("function env(name) {")
            appendLine("  if (typeof process !== \"undefined\" && process && process.env && process.env[name]) return process.env[name]")
            appendLine("  if (typeof Bun !== \"undefined\" && Bun && Bun.env) return Bun.env[name] || \"\"")
            appendLine("  return \"\"")
            appendLine("}")
            appendLine()
            appendLine("function config() {")
            appendLine("  return {")
            appendLine("    port: env(\"AITT_PORT\"),")
            appendLine("    token: env(\"AITT_TOKEN\"),")
            appendLine("    tabId: env(\"AITT_TAB_ID\")")
            appendLine("  }")
            appendLine("}")
            appendLine()
            appendLine("async function post(type, extra) {")
            appendLine("  var cfg = config()")
            appendLine("  if (!cfg.port || !cfg.token || !cfg.tabId) return")
            appendLine("  if (!extra) extra = {}")
            appendLine("  extra.source = \"opencode\"")
            appendLine("  extra.type = type")
            appendLine("  extra.tabId = cfg.tabId")
            appendLine("  try {")
            appendLine("    await fetch(\"http://127.0.0.1:\" + cfg.port + \"/event\", {")
            appendLine("      method: \"POST\",")
            appendLine("      headers: {")
            appendLine("        \"content-type\": \"application/json\",")
            appendLine("        \"x-aitt-token\": cfg.token")
            appendLine("      },")
            appendLine("      body: JSON.stringify(extra)")
            appendLine("    })")
            appendLine("  } catch (_) {}")
            appendLine("}")
            appendLine()
            appendLine("function sessionID(ev) {")
            appendLine("  return (ev && ev.properties && (ev.properties.sessionID || ev.properties.sessionId)) ||")
            appendLine("    (ev && (ev.sessionID || ev.sessionId)) || \"\"")
            appendLine("}")
            appendLine()
            appendLine("function extractPaths(obj, result) {")
            appendLine("  if (!result) result = []")
            appendLine("  if (!obj || typeof obj !== \"object\") return result")
            appendLine("  for (var key in obj) {")
            appendLine("    var val = obj[key]")
            appendLine("    if (typeof val === \"string\" && val.length > 0) {")
            appendLine("      var kl = key.toLowerCase()")
            appendLine("      if (kl === \"file\" || kl === \"path\" || kl === \"filepath\" ||")
            appendLine("          kl === \"file_path\" || kl === \"filename\" || kl === \"file_name\" ||")
            appendLine("          kl.indexOf(\"file\") >= 0 || kl.indexOf(\"path\") >= 0 ||")
            appendLine("          val.indexOf(\"/\") >= 0 || val.indexOf(\"\\\\\") >= 0 ||")
            appendLine("          val.indexOf(\"./\") === 0 || val.indexOf(\"../\") === 0) {")
            appendLine("        if (val.length < 500 && val.indexOf(\"\\n\") < 0 &&")
            appendLine("            val.indexOf(\"{\") !== 0 && val.indexOf(\"[\") !== 0) {")
            appendLine("          result.push(val)")
            appendLine("        }")
            appendLine("      }")
            appendLine("    } else if (Array.isArray(val)) {")
            appendLine("      for (var i = 0; i < val.length; i++) extractPaths(val[i], result)")
            appendLine("    } else if (typeof val === \"object\" && val !== null) {")
            appendLine("      extractPaths(val, result)")
            appendLine("    }")
            appendLine("  }")
            appendLine("  return result")
            appendLine("}")
            appendLine()
            appendLine("function unique(arr) {")
            appendLine("  var seen = {}")
            appendLine("  var out = []")
            appendLine("  for (var i = 0; i < arr.length; i++) {")
            appendLine("    if (!seen[arr[i]]) { seen[arr[i]] = true; out.push(arr[i]) }")
            appendLine("  }")
            appendLine("  return out")
            appendLine("}")
            appendLine()
            appendLine("export var AiTerminalTools = async function() {")
            appendLine("  return {")
            appendLine("    event: async function(ctx) {")
            appendLine("      var ev = ctx.event")
            appendLine("      if (!ev) return")
            appendLine()
            appendLine("      if (ev.type === \"session.status\") {")
            appendLine("        var status = ev.properties && ev.properties.status")
            appendLine("        if (status && status.type === \"busy\") {")
            appendLine("          await post(\"turn_start\", { sessionID: sessionID(ev) })")
            appendLine("        }")
            appendLine("        return")
            appendLine("      }")
            appendLine()
            appendLine("      if (ev.type === \"session.idle\") {")
            appendLine("        await post(\"turn_end\", { sessionID: sessionID(ev) })")
            appendLine("        return")
            appendLine("      }")
            appendLine()
            appendLine("      if (ev.type === \"file.edited\") {")
            appendLine("        var file = ev.properties && ev.properties.file")
            appendLine("        if (file) await post(\"file_changed\", { paths: [file], sessionID: sessionID(ev) })")
            appendLine("      }")
            appendLine("    },")
            appendLine()
            appendLine("    \"tool.execute.before\": async function(input, output) {")
            appendLine("      var paths = unique(extractPaths(output && output.args))")
            appendLine("      if (paths.length > 0) {")
            appendLine("        await post(\"before_write\", { paths: paths, sessionID: input && input.sessionID })")
            appendLine("      }")
            appendLine("    },")
            appendLine()
            appendLine("    \"tool.execute.after\": async function(input, output) {")
            appendLine("      var paths = unique(")
            appendLine("        extractPaths(input && input.args)")
            appendLine("          .concat(extractPaths(output && output.metadata))")
            appendLine("          .concat(extractPaths({ output: output && output.output }))")
            appendLine("      )")
            appendLine("      if (paths.length > 0) {")
            appendLine("        await post(\"file_changed\", { paths: paths, sessionID: input && input.sessionID })")
            appendLine("      }")
            appendLine("    }")
            appendLine("  }")
            appendLine("}")
        }

        Files.writeString(pluginFile, js)
        log.info("Written OpenCode JS plugin to $pluginFile")
    }

    private fun writeLauncherScripts(
        toolsDir: Path, tabId: String, token: String, port: Int
    ): AiTurnHookInstaller.LauncherPaths {
        val cmdFile = toolsDir.resolve("run-opencode-$tabId.cmd")
        val shFile = toolsDir.resolve("run-opencode-$tabId.sh")

        Files.writeString(cmdFile, buildString {
            appendLine("@echo off")
            appendLine("set AITT_PORT=$port")
            appendLine("set AITT_TOKEN=$token")
            appendLine("set AITT_TAB_ID=$tabId")
            appendLine("set AITT_TOOL=opencode")
            appendLine("opencode")
        })

        // launcher 负责把当前 tab 的鉴权和路由信息注入 OpenCode 进程环境。
        Files.writeString(shFile, buildString {
            appendLine("#!/usr/bin/env bash")
            appendLine("export AITT_PORT=\"$port\"")
            appendLine("export AITT_TOKEN=\"$token\"")
            appendLine("export AITT_TAB_ID=\"$tabId\"")
            appendLine("export AITT_TOOL=\"opencode\"")
            appendLine("exec opencode")
        })
        setExecutableIfPosix(shFile)

        return AiTurnHookInstaller.LauncherPaths(cmdPath = cmdFile, shPath = shFile)
    }

    fun cleanupLauncherScripts(tabId: String) {
        val projectBasePath = project.basePath ?: return
        val toolsDir = Path.of(projectBasePath).resolve(".idea").resolve("ai-terminal-tools")
        try {
            Files.deleteIfExists(toolsDir.resolve("run-opencode-$tabId.cmd"))
            Files.deleteIfExists(toolsDir.resolve("run-opencode-$tabId.sh"))
        } catch (_: Throwable) {
        }
    }

    private fun setExecutableIfPosix(path: Path) {
        try {
            val perms = Files.getPosixFilePermissions(path).toMutableSet()
            perms.add(PosixFilePermission.OWNER_EXECUTE)
            perms.add(PosixFilePermission.GROUP_EXECUTE)
            Files.setPosixFilePermissions(path, perms)
        } catch (_: Throwable) {
        }
    }
}
